# Exploratory Data Analysis

In [ ]:
# Preview the top 5 rows and load dataset
import pandas as pd
import numpy as n
df = pd.read_csv('../data/raw/Sales.csv')
df.head()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [3]:
df.shape

(113036, 18)

In [ ]:
#Structural Dimensions & Schema Types
print(f"Total Rows: {df.shape[0]}, Total Columns: {df.shape[1]}")
df.info()

Total Rows: 113036, Total Columns: 18
<class 'pandas.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  str
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  str
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  str
 6   Customer_Gender   113036 non-null  str
 7   Country           113036 non-null  str
 8   State             113036 non-null  str
 9   Product_Category  113036 non-null  str
 10  Sub_Category      113036 non-null  str
 11  Product           113036 non-null  str
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), str(9)
memory usage: 15.5 MB

In [ ]:
#Check for Missing/Null Values
null_counts = df.isnull().sum()
print("Null values per column:")
print(null_counts[null_counts > 0])

Null values per column:
Series([], dtype: int64)

In [ ]:
#Statistics
df.describe()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000
mean,15.665753,2014.401739,35.919212,11.901660,267.296366,452.938427,285.051665,469.318695,754.370360
std,8.781567,1.272510,11.021936,9.561857,549.835483,922.071219,453.887443,884.866118,1309.094674
min,1.000000,2011.000000,17.000000,1.000000,1.000000,2.000000,-30.000000,1.000000,2.000000
25%,8.000000,2013.000000,28.000000,2.000000,2.000000,5.000000,29.000000,28.000000,63.000000
50%,16.000000,2014.000000,35.000000,10.000000,9.000000,24.000000,101.000000,108.000000,223.000000
75%,23.000000,2016.000000,43.000000,20.000000,42.000000,70.000000,358.000000,432.000000,800.000000
max,31.000000,2016.000000,87.000000,32.000000,2171.000000,3578.000000,15096.000000,42978.000000,58074.000000

In [ ]:
#unique values 
print("Unique Countries:", df['Country'].unique())
print("\nOrders per Country:")
print(df['Country'].value_counts())

Unique Countries: <StringArray>
['Canada', 'Australia', 'United States', 'Germany', 'France',
 'United Kingdom']
Length: 6, dtype: str

Orders per Country:
Country
United States     39206
Australia         23936
Canada            14178
United Kingdom    13620
Germany           11098
France            10998
Name: count, dtype: int64

In [ ]:
#group by Country and State to get total Revenue and Profit
sales_by_region = df.groupby(['Country', 'State'])[['Revenue', 'Profit']].sum().reset_index()
sales_by_region.sort_values(by='Revenue', ascending=False).head(10)

           Country             State   Revenue   Profit
33   United States        California  17672620  7772869
30  United Kingdom           England  10646196  4413853
0        Australia   New South Wales   9203495  3133684
6           Canada  British Columbia   7877890  3693348
51   United States        Washington   6741510  1997550
1        Australia        Queensland   5066267  1619158
4        Australia          Victoria   5054839  1428026
46   United States            Oregon   3450410  1258168
27         Germany            Hessen   2073391   813402
29         Germany          Saarland   2029545   634294